site_name: ![FluxoScript Logo](./img/logo_fluxo.jfif){: style="height:150px;width:150px"} Votre Site de Documentation
nav:
  - Accueil: index.md
  - Page de Test: test.md

markdown_extensions:
  - attr_list